require: rubocop-rails

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "lib/tasks/**/*"
    - "spec/**/*"
    - "config/initializers/simple_form_bootstrap.rb"
    - "db/**/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Layout/LineLength:
  Max: 90
  IgnoredPatterns:
    - '\A(\s)*#'
  Exclude:
    - "db/**/*"
    - "config/initializers/simple_form.rb"
    - "config/initializers/simple_form_bootstrap.rb"

Rails/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
